name: Release

on:
    workflow_dispatch:

jobs:
    release:
        if: github.repository == 'Act-Aks/actlib'
        runs-on: ubuntu-latest
        permissions:
            contents: write
            id-token: write
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  cache: 'yarn'

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  cache: 'yarn'
                  node-version-file: .nvmrc
                  registry-url: https://registry.npmjs.org/

            - name: Install dependencies
              run: yarn install --immutable

            - uses: ExpediaGroup/package-json-validator@v1.10.0
              with:
                  rules: |
                      ranges
                      tags
                  dependency-types: |
                      dependencies
                      devDependencies
                  ignore-packages: |
                      @jscutlery/semv
                  allowed-ranges: ^

            - name: Sets the base and head SHAs for the nx affected commands in CI
              uses: nrwl/nx-set-shas@v4

            - name: Lint
              run: yarn nx affected -t lint

            - name: Print Environment Info
              run: yarn nx report

            - name: Configure Git User
              run: |
                  git config --global user.email 'akashsrivastava.git@gmail.com'
                  git config --global user.name 'Act-Aks'

            - name: Release packages
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
                  NPM_CONFIG_PROVENANCE: true
              run: yarn release
